# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJ0mujpLFBEDh7LTEVXVnnPP1ayX5-Ka
"""

# Solicitar nome
nome = input("Digite o seu nome: ")

# Verificar idade em um loop até que seja maior ou igual a 18
while True:
    idade = int(input("Digite sua idade: "))
    if idade < 18:
        print(f"Desculpe, {nome}, você não tem permissão para acessar a calculadora.")
    else:
        print(f"Acesso liberado, {nome}! Você pode utilizar a calculadora.")
        break

# Acessando a calculadora
continuar = "s"
while continuar == "s":
    numero1 = float(input("Digite o primeiro número: "))
    numero2 = float(input("Digite o segundo número: "))

    print("\nEscolha a operação desejada: ")
    print("1 - Soma")
    print("2 - Subtração")
    print("3 - Multiplicação")
    print("4 - Divisão")

    operação = input("Escolha a opção (1/2/3/4): ")

    if operação == "1":
        resultado = numero1 + numero2
        print(f"{nome}, o resultado da soma é: {resultado}")
    elif operação == "2":
        resultado = numero1 - numero2
        print(f"{nome}, o resultado da subtração é: {resultado}")
    elif operação == "3":
        resultado = numero1 * numero2
        print(f"{nome}, o resultado da multiplicação é: {resultado}")
    elif operação == "4":
        if numero2 != 0:
            resultado = numero1 / numero2
            print(f"{nome}, o resultado da divisão é: {resultado}")
        else:
            print("Erro: não é possível dividir por zero.")
    else:
        print("Opção inválida. Tente novamente.")

    continuar = input(f"{nome}, deseja realizar outra operação? (s/n): ")

print(f"{nome}, obrigado por utilizar a calculadora!")

